/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.*;
import MethodBarang.BarangControl;
import MethodBarang.DataBarang;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Kelompok 1
 */
public class Barang extends javax.swing.JInternalFrame {
    int x = 0;
    private DefaultTableModel model;
    BarangControl bc = new BarangControl();
    DataBarang DB = new DataBarang();
    List<DataBarang> ListBarang = new ArrayList<DataBarang>();
    /**
     * Creates new form Barang
     */
    public Barang() throws SQLException {
        initComponents();
        buatTable();
        showTable();
        lebarKolom();
        tanggal();
        bersih();
        siapIsi(false);
        tombolNormal();
        tampilx();
    }
    
    
        public void tanggal(){
        Date tgl = new Date();
        txtTanggal.setDate(tgl);
    }
    
    private void buatTable() {
        model = new DefaultTableModel();
        model.addColumn("Tanggal_Masuk");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Jenis");
        model.addColumn("Stok");
        model.addColumn("Harga");
        model.addColumn("Kadaluwarsa");
        tblBarang.setModel(model);
        lebarKolom();
    }
    
    private void showTable() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ListBarang.clear();
        ListBarang = bc.tampil();
        for (x=0; x<ListBarang.size(); x++) {
            Object[] data = new Object[7];
            data[0]=ListBarang.get(x).getTanggal();
            data[1]=ListBarang.get(x).getKdBarang();
            data[2]=ListBarang.get(x).getNmBarang();
            data[3]=ListBarang.get(x).getJenis();
            data[4]=ListBarang.get(x).getStok();
            data[5]=ListBarang.get(x).getHarga();
            data[6]=ListBarang.get(x).getKadaluwarsa();
            model.addRow(data);
        }
        lebarKolom();
    }
    
        public void lebarKolom(){
        TableColumn column;
        tblBarang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tblBarang.getColumnModel().getColumn(0);
        column.setPreferredWidth(115);
        column = tblBarang.getColumnModel().getColumn(1);
        column.setPreferredWidth(100);
        column = tblBarang.getColumnModel().getColumn(2);
        column.setPreferredWidth(500);
        column = tblBarang.getColumnModel().getColumn(3);
        column.setPreferredWidth(105);
        column = tblBarang.getColumnModel().getColumn(4);
        column.setPreferredWidth(105);
        column = tblBarang.getColumnModel().getColumn(5);
        column.setPreferredWidth(110); 
        column = tblBarang.getColumnModel().getColumn(6);
        column.setPreferredWidth(115);
        tblBarang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
    }
   
    private void buatKdBarang() {
        ListBarang = bc.tampil();
        int a = ListBarang.size()-1;
        int no = Integer.parseInt(ListBarang.get(a).getKdBarang().replace("BR-", ""))+1;
        txtKdBarang.setText("BR-"+no);
        txtKdBarang.setEnabled(false);
    }
    
    private void siapIsi(boolean a) {
        txtKdBarang.setEnabled(a);
        txtNmBarang.setEnabled(a);
        cmbJenis.setEnabled(a);
        txtStok.setEnabled(a);
        txtHarga.setEnabled(a);
        txtTanggal.setEnabled(a);
        txtKadaluwarsa.setEnabled(a);
    }
    
    private void bersih() {
        txtKdBarang.setText("");
        txtNmBarang.setText("");
        cmbJenis.setSelectedItem("Pilih");
        txtStok.setText("");
        txtHarga.setText("");
        txtTanggal.setDate(null);
        txtKadaluwarsa.setDate(null);
    }
    
    private void tombolNormal() {
        btnSimpan.setEnabled(false);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
    }
    
    private void tombolKembali() {
        btnSimpan.setEnabled(true);
        btnHapus.setEnabled(true);
    }
    
    public void tampilx () throws SQLException {
        int jmlBarang = bc.getJumlahBarang();
        txtJumlah.setText(String.valueOf(jmlBarang));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        cmbJenis = new javax.swing.JComboBox<>();
        txtJumlah = new javax.swing.JLabel();
        txtNmBarang = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        txtKdBarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtKadaluwarsa = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setTitle("PRODUCT");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHapus.setBackground(new java.awt.Color(122, 72, 221));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, 110, 50));

        btnEdit.setBackground(new java.awt.Color(122, 72, 221));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, 110, 50));

        btnSimpan.setBackground(new java.awt.Color(122, 72, 221));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Save");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 110, 50));

        btnTambah.setBackground(new java.awt.Color(122, 72, 221));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Add");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 110, 50));

        cmbJenis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Cair", "Kapsul", "Kental" }));
        jPanel1.add(cmbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 120, 35));

        txtJumlah.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        txtJumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJumlah.setText("Jumlah");
        jPanel1.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 590, 290, 120));

        txtNmBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtNmBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 310, 35));

        txtCari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, 310, 35));

        txtKdBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtKdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 310, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Nama Barang");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setText("Cari Barang");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 130, 35));

        txtStok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, 310, 35));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Jumlah Barang");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, 150, 35));

        txtHarga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 310, 35));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setText("Kadaluwarsa");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, 35));

        tblBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblBarang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.setFocusable(false);
        tblBarang.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblBarang.setRowHeight(30);
        tblBarang.setSelectionBackground(new java.awt.Color(122, 72, 221));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1160, 200));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Kode Barang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 140, 35));

        txtKadaluwarsa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtKadaluwarsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 310, 35));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setText("Jenis");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 120, 35));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setText("Harga");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 70, 35));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel14.setText("Stok");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 70, 35));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setText("Tanggal Masuk");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 35));

        txtTanggal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 310, 35));

        jPanel2.setBackground(new java.awt.Color(122, 72, 221));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kelompok 1 @2021");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 733, 1230, 33));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1230, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        SimpleDateFormat format=new SimpleDateFormat("dd-MM-yyyy");
        String tanggal = String.valueOf(format.format(txtTanggal.getDate()));
        if (txtNmBarang.getText().isEmpty() || cmbJenis.getSelectedItem().equals("Pilih") || txtStok.getText().isEmpty()
            || txtHarga.getText().isEmpty() || txtKadaluwarsa.getDate().equals("")){
            JOptionPane.showMessageDialog(null, "Data Cannot Be Empty", "Monascho Store", JOptionPane.WARNING_MESSAGE);
        }else{
            DB.setKdBarang(txtKdBarang.getText());
            DB.setNmBarang(txtNmBarang.getText());
            DB.setJenis(cmbJenis.getSelectedItem().toString());
            DB.setStok(Integer.parseInt(txtStok.getText()));
            DB.setHarga(Integer.parseInt(txtHarga.getText()));
            DB.setTanggal(format.format(txtTanggal.getDate()));
            DB.setKadaluwarsa(format.format(txtKadaluwarsa.getDate()));
            if (btnTambah.getText().equalsIgnoreCase("Cancel")) {
                if(bc.tambahBarang(DB)==1) {
                    JOptionPane.showMessageDialog(null, "Data Has Been Saved", "Monascho Store", JOptionPane.INFORMATION_MESSAGE);
                    buatTable();
                    showTable();
                    lebarKolom();
                    try {
                        tampilx();
                    } catch (Exception e) {
                        Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, e);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Data Failed to Save", "Monascho Store", JOptionPane.WARNING_MESSAGE);
                }
            }
            if (btnEdit.getText().equalsIgnoreCase("Cancel")) {
                if (bc.editBarang(DB)==1) {
                    JOptionPane.showMessageDialog(null, "Data Has Been Changed", "Monascho Store", JOptionPane.INFORMATION_MESSAGE);
                    buatTable();
                    showTable();
                }else{
                    JOptionPane.showMessageDialog(null, "Data Failed to Change", "Monascho Store", JOptionPane.WARNING_MESSAGE);
                }
            }
            bersih();
            siapIsi(false);
            btnTambah.setText("Add");
            btnEdit.setText("Edit");
            tombolNormal();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if(btnTambah.getText().equalsIgnoreCase("Add")) {
            btnTambah.setText("Cancel");
            bersih();
            tanggal();
            siapIsi(true);
            buatKdBarang();
            txtNmBarang.requestFocus();
            tombolKembali();
        }else{
            btnTambah.setText("Add");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int baris = tblBarang.getSelectedRow();
        String dateValue = String.valueOf(tblBarang.getValueAt(tblBarang.getSelectedRow(), 0));
        txtKdBarang.setText(tblBarang.getModel().getValueAt(baris, 1).toString());
        txtNmBarang.setText(tblBarang.getModel().getValueAt(baris, 2).toString());
        cmbJenis.setSelectedItem(tblBarang.getModel().getValueAt(baris, 3).toString());
        txtStok.setText(tblBarang.getModel().getValueAt(baris, 4).toString());
        txtHarga.setText(tblBarang.getModel().getValueAt(baris, 5).toString());
        String dateValue1 = String.valueOf(tblBarang.getValueAt(tblBarang.getSelectedRow(), 6));
        java.util.Date date = null;
        try {
            date = new SimpleDateFormat("dd-MM-yyyy").parse(dateValue);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        txtTanggal.setDate(date);
        try {
            date = new SimpleDateFormat("dd-MM-yyyy").parse(dateValue1);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        txtKadaluwarsa.setDate(date);
        lebarKolom();
        siapIsi(false);
        btnHapus.setEnabled(true);
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
         if (btnEdit.getText().equalsIgnoreCase("Edit")) {
            btnEdit.setText("Cancel");
            siapIsi(true);
            txtKdBarang.setEnabled(false);
            txtNmBarang.requestFocus();
            btnTambah.setEnabled(true);
            btnSimpan.setEnabled(true);
            btnHapus.setEnabled(false);
            btnEdit.setEnabled(true);
        }else{
            btnEdit.setText("Edit");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DB.setKdBarang(txtKdBarang.getText());
        int pesan = JOptionPane.showConfirmDialog(null, "Are You Sure Want to Delete This ?","Monascho Store",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (pesan == JOptionPane.YES_NO_OPTION) {
            if (bc.deleteBarang(DB)==1) {
                JOptionPane.showMessageDialog(null, "Data Has Been Deleted", "Monascho Store", JOptionPane.INFORMATION_MESSAGE);
                bersih();
                siapIsi(false);
                tombolNormal();
                buatTable();
                showTable();
                lebarKolom();
            try {
                tampilx();
            } catch (SQLException ex) {
                Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
                JOptionPane.showMessageDialog(null, "Data Failed to Delete", "Monascho Store", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        String cari = null;
        cari = txtCari.getText();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ListBarang.clear();
        ListBarang = bc.cariBarang(cari);
        for (x=0; x<ListBarang.size(); x++) {
            Object[] data = new Object[7];
            data[0] = ListBarang.get(x).getTanggal();
            data[1] = ListBarang.get(x).getKdBarang();
            data[2] = ListBarang.get(x).getNmBarang();
            data[3] = ListBarang.get(x).getJenis();
            data[4] = ListBarang.get(x).getStok();
            data[5] = ListBarang.get(x).getHarga();
            data[6] = ListBarang.get(x).getKadaluwarsa();
            model.addRow(data);
        }
        lebarKolom();
    }//GEN-LAST:event_txtCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JLabel txtJumlah;
    private com.toedter.calendar.JDateChooser txtKadaluwarsa;
    private javax.swing.JTextField txtKdBarang;
    private javax.swing.JTextField txtNmBarang;
    private javax.swing.JTextField txtStok;
    private com.toedter.calendar.JDateChooser txtTanggal;
    // End of variables declaration//GEN-END:variables
}
