/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author firda
 */
public class MenuUtama1 extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama1() {
        initComponents();
        getjam();
    }
    
    public void tampilUser(String user) {
        lbl_Sebagai.setText(user);
    }
    
    public void getjam() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MM-YYYY");
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam<=9) {
                    nol_jam = "0";
                }
                if (nilai_menit<=9) {
                    nol_menit = "0";
                }
                if (nilai_detik<=9) {
                    nol_detik = "0";
                }
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                lbl_jam.setText(""+jam+" : "+menit+" : "+detik+"    ");
                lbl_tgl.setText(tgl.format(dt));
            }
        };
        new javax.swing.Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        JDashboard = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Transaksi = new javax.swing.JPanel();
        JTransaksi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Keluar = new javax.swing.JPanel();
        JKeluar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_tgl = new javax.swing.JLabel();
        lbl_Sebagai = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_jam = new javax.swing.JLabel();
        about = new javax.swing.JPanel();
        Jabout = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        JLogout = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Pengguna = new javax.swing.JPanel();
        JPengguna = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DataBarang = new javax.swing.JPanel();
        JDataBarang = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Laporan = new javax.swing.JPanel();
        JLaporan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jDashboard = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(64, 43, 100));
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DashboardMousePressed(evt);
            }
        });
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JDashboard.setBackground(new java.awt.Color(0, 0, 0));
        JDashboard.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        JDashboard.setForeground(new java.awt.Color(255, 255, 255));
        JDashboard.setText("Home");
        Dashboard.add(JDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_home_40px_3.png"))); // NOI18N
        Dashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jPanel1.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 370, 70));

        Transaksi.setBackground(new java.awt.Color(64, 43, 100));
        Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransaksiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TransaksiMousePressed(evt);
            }
        });
        Transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        JTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        JTransaksi.setText("Transaction");
        Transaksi.add(JTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_transaction_40px.png"))); // NOI18N
        Transaksi.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jPanel1.add(Transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 370, 70));

        Keluar.setBackground(new java.awt.Color(64, 43, 100));
        Keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KeluarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KeluarMousePressed(evt);
            }
        });
        Keluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JKeluar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        JKeluar.setForeground(new java.awt.Color(255, 255, 255));
        JKeluar.setText("Exit");
        Keluar.add(JKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_exit_40px.png"))); // NOI18N
        Keluar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jPanel1.add(Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 370, 70));

        jPanel9.setBackground(new java.awt.Color(64, 43, 100));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_tgl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tgl.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tgl.setText("Tanggal");
        jPanel9.add(lbl_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 250, 30));

        lbl_Sebagai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Sebagai.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Sebagai.setText("Sebagai");
        jPanel9.add(lbl_Sebagai, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_user_30px.png"))); // NOI18N
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_clock_30px.png"))); // NOI18N
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 30, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_calendar_30px.png"))); // NOI18N
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, 30));

        lbl_jam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_jam.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jam.setText("Jam");
        jPanel9.add(lbl_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 180, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 150));

        about.setBackground(new java.awt.Color(64, 43, 100));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutMousePressed(evt);
            }
        });
        about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jabout.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Jabout.setForeground(new java.awt.Color(255, 255, 255));
        Jabout.setText("About");
        about.add(Jabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_about_40px.png"))); // NOI18N
        about.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jPanel1.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 370, 70));

        Logout.setBackground(new java.awt.Color(64, 43, 100));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoutMousePressed(evt);
            }
        });
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLogout.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        JLogout.setForeground(new java.awt.Color(255, 255, 255));
        JLogout.setText("Logout");
        Logout.add(JLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_logout_rounded_left_40px.png"))); // NOI18N
        Logout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 370, 70));

        Pengguna.setBackground(new java.awt.Color(64, 43, 100));
        Pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PenggunaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PenggunaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PenggunaMousePressed(evt);
            }
        });
        Pengguna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPengguna.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        JPengguna.setForeground(new java.awt.Color(255, 255, 255));
        JPengguna.setText("Employee");
        Pengguna.add(JPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 180, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_user_groups_40px.png"))); // NOI18N
        Pengguna.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jPanel1.add(Pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 370, 70));

        DataBarang.setBackground(new java.awt.Color(64, 43, 100));
        DataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataBarangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DataBarangMousePressed(evt);
            }
        });
        DataBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JDataBarang.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        JDataBarang.setForeground(new java.awt.Color(255, 255, 255));
        JDataBarang.setText("Product");
        DataBarang.add(JDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 210, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_product_40px.png"))); // NOI18N
        DataBarang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jPanel1.add(DataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 370, 70));

        Laporan.setBackground(new java.awt.Color(64, 43, 100));
        Laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LaporanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LaporanMousePressed(evt);
            }
        });
        Laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLaporan.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        JLaporan.setForeground(new java.awt.Color(255, 255, 255));
        JLaporan.setText("Report");
        Laporan.add(JLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_report_file_40px.png"))); // NOI18N
        Laporan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jPanel1.add(Laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 370, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 900));

        jPanel2.setBackground(new java.awt.Color(122, 72, 221));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 65)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("MONASCHO STORE");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1230, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 1230, 150));

        jDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 80)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Welcome to");
        jDashboard.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1230, 170));

        jLabel17.setFont(new java.awt.Font("Ink Free", 1, 65)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("\"Monascho Admin Management\"");
        jDashboard.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1230, 160));

        jPanel3.setBackground(new java.awt.Color(122, 72, 221));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_thermometer_man_100px.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 140, 120));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_groups_100px.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 120));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_Hospital_100px.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 140, 120));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_Right_Arrow_100px.png"))); // NOI18N
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 140, 120));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_orange_juice_100px.png"))); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 140, 120));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_Standing_Man_100px.png"))); // NOI18N
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 140, 120));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_Down_Left_100px.png"))); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 140, 120));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_Right_Arrow_100px.png"))); // NOI18N
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 140, 120));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_Buying_100px.png"))); // NOI18N
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 140, 120));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_man_drinking_water_100px.png"))); // NOI18N
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 140, 120));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_Right_Arrow_100px.png"))); // NOI18N
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 140, 120));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_Long_Arrow_Left_100px.png"))); // NOI18N
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 140, 120));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_Arrow_Up_100px_1.png"))); // NOI18N
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, 120));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconMenu/icons8_Long_Arrow_Left_100px.png"))); // NOI18N
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 140, 120));

        jDashboard.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1230, 290));

        jPanel4.setBackground(new java.awt.Color(122, 72, 221));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Kelompok 1 @2021");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 30));

        jDashboard.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1230, 33));

        getContentPane().add(jDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 1230, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseEntered
        // TODO add your handling code here:
        JDashboard.setForeground(Color.white);
        Dashboard.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_DashboardMouseEntered

    private void DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseExited
        // TODO add your handling code here:
        JDashboard.setForeground(Color.white);
        Dashboard.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_DashboardMouseExited

    private void TransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiMouseEntered
        // TODO add your handling code here:
        JTransaksi.setForeground(Color.white);
        Transaksi.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_TransaksiMouseEntered

    private void TransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiMouseExited
        // TODO add your handling code here:
        JTransaksi.setForeground(Color.white);
        Transaksi.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_TransaksiMouseExited

    private void KeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMouseEntered
        // TODO add your handling code here:
        JKeluar.setForeground(Color.white);
        Keluar.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_KeluarMouseEntered

    private void KeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMouseExited
        // TODO add your handling code here:
        JKeluar.setForeground(Color.white);
        Keluar.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_KeluarMouseExited

    private void aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseEntered
        // TODO add your handling code here:
        Jabout.setForeground(Color.white);
        about.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_aboutMouseEntered

    private void aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseExited
        // TODO add your handling code here:
        Jabout.setForeground(Color.white);
        about.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_aboutMouseExited

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        // TODO add your handling code here:
        JLogout.setForeground(Color.white);
        Logout.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        // TODO add your handling code here:
        JLogout.setForeground(Color.white);
        Logout.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_LogoutMouseExited

    private void KeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMousePressed
        // TODO add your handling code here:
        int confirm =JOptionPane.showConfirmDialog(this,"Are You Sure Want to Exit ?","Monascho Store",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION){
            System.exit(0);
        }if(confirm == JOptionPane.NO_OPTION){   
        } 
    }//GEN-LAST:event_KeluarMousePressed

    private void LogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMousePressed
        // TODO add your handling code here:
        int confirm =JOptionPane.showConfirmDialog(this,"Are You Sure Want to Logout ?","Monascho Store",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION){
            System.exit(0);
        }if(confirm == JOptionPane.NO_OPTION){   
        jDashboard.removeAll();
        jDashboard.repaint();
        this.setVisible(false);
        Loading ld = new Loading();
        ld.setVisible(true);
        }
    }//GEN-LAST:event_LogoutMousePressed

    private void TransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiMousePressed
        // TODO add your handling code here:
        jDashboard.removeAll();
        jDashboard.repaint();
        Transaksi tr = new Transaksi();
        tr.setVisible(true);     
        jDashboard.add(tr);
    }//GEN-LAST:event_TransaksiMousePressed

    private void PenggunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenggunaMouseEntered
        // TODO add your handling code here:
        JPengguna.setForeground(Color.white);
        Pengguna.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_PenggunaMouseEntered

    private void PenggunaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenggunaMouseExited
        // TODO add your handling code here:
        JPengguna.setForeground(Color.white);
        Pengguna.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_PenggunaMouseExited

    private void PenggunaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenggunaMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You Have to Login as Admin", "MONASCHO STORE", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_PenggunaMousePressed

    private void DataBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataBarangMouseEntered
        // TODO add your handling code here:
        JDataBarang.setForeground(Color.white);
        DataBarang.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_DataBarangMouseEntered

    private void DataBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataBarangMouseExited
        // TODO add your handling code here:
        JDataBarang.setForeground(Color.white);
        DataBarang.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_DataBarangMouseExited

    private void DataBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataBarangMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You Have to Login as Admin", "MONASCHO STORE", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_DataBarangMousePressed

    private void LaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMouseEntered
        // TODO add your handling code here:
        JLaporan.setForeground(Color.white);
        Laporan.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_LaporanMouseEntered

    private void LaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMouseExited
        // TODO add your handling code here:
        JLaporan.setForeground(Color.white);
        Laporan.setBackground(new Color(64,43,100));
    }//GEN-LAST:event_LaporanMouseExited

    private void LaporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You Have to Login as Admin", "MONASCHO STORE", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_LaporanMousePressed

    private void DashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMousePressed
        // TODO add your handling code here:
        jDashboard.removeAll();
        jDashboard.repaint();
        Dashboard1 tr = new Dashboard1();
        tr.setVisible(true);     
        jDashboard.add(tr);
    }//GEN-LAST:event_DashboardMousePressed

    private void aboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMousePressed
        // TODO add your handling code here:
        jDashboard.removeAll();
        jDashboard.repaint();
        About pg = new About();
        pg.setVisible(true);
        jDashboard.add(pg);
    }//GEN-LAST:event_aboutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel DataBarang;
    private javax.swing.JLabel JDashboard;
    private javax.swing.JLabel JDataBarang;
    private javax.swing.JLabel JKeluar;
    private javax.swing.JLabel JLaporan;
    private javax.swing.JLabel JLogout;
    private javax.swing.JLabel JPengguna;
    private javax.swing.JLabel JTransaksi;
    private javax.swing.JLabel Jabout;
    private javax.swing.JPanel Keluar;
    private javax.swing.JPanel Laporan;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel Pengguna;
    private javax.swing.JPanel Transaksi;
    private javax.swing.JPanel about;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jDashboard;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_Sebagai;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_tgl;
    // End of variables declaration//GEN-END:variables
}
